server:
  port: 9090

spring:
  application:
    name: batch-processing

  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false